version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://api-gateway:3000/api
        - NEXT_PUBLIC_AUTH_API_URL=http://api-gateway:3000/api/auth
        - NEXT_PUBLIC_TENANT_API_URL=http://api-gateway:3000/api/tenant
        - NEXT_PUBLIC_USER_API_URL=http://api-gateway:3000/api/user
        - NEXT_PUBLIC_FILE_API_URL=http://api-gateway:3000/api/file
        - API_GATEWAY_URL=http://api-gateway:3000
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://api-gateway:3000/api
      - NEXT_PUBLIC_AUTH_API_URL=http://api-gateway:3000/api/auth
      - NEXT_PUBLIC_TENANT_API_URL=http://api-gateway:3000/api/tenant
      - NEXT_PUBLIC_USER_API_URL=http://api-gateway:3000/api/user
      - NEXT_PUBLIC_FILE_API_URL=http://api-gateway:3000/api/file
      - API_GATEWAY_URL=http://api-gateway:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - multi-tenant-network

networks:
  multi-tenant-network:
    external: true
