version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - auth-network

  postgres:
    image: postgres:15
    container_name: auth-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${SYSTEM_DB_USERNAME}
      POSTGRES_PASSWORD: ${SYSTEM_DB_PASSWORD}
      POSTGRES_DB: ${SYSTEM_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - auth-network

  redis:
    image: redis:7-alpine
    container_name: auth-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - auth-network

volumes:
  postgres-data:
  redis-data:

networks:
  auth-network:
