apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-database-pvc
  namespace: multi-tenant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
