apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-database
  namespace: multi-tenant
  labels:
    app: kong-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kong-database
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: kong-database-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-database-credentials
              key: password
        - name: POSTGRES_DB
          value: "kong"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: kong-database-data
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: kong-database-data
        persistentVolumeClaim:
          claimName: kong-database-pvc
