apiVersion: v1
kind: Service
metadata:
  name: kong-database
  namespace: multi-tenant
  labels:
    app: kong-database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: kong-database
