apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
  namespace: multi-tenant
  labels:
    app: kong-gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8100"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: proxy-ssl
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: admin-ssl
    port: 8444
    targetPort: 8444
    protocol: TCP
  - name: metrics
    port: 8100
    targetPort: 8100
    protocol: TCP
  selector:
    app: kong-gateway
