apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-plugins-source
  namespace: multi-tenant
data:
  # This ConfigMap will be populated with the plugin source code files
  # You would need to add each plugin's files here, but for demonstration, 
  # we'll just include placeholders for the handlers
  "tenant-identifier/handler.lua": |
    -- Custom Kong plugin for tenant identification
    -- Full implementation would be provided during deployment
    local plugin = {
      PRIORITY = 1000,
      VERSION = "1.0.0"
    }
    -- ...

  "tenant-jwt-validator/handler.lua": |
    -- Custom Kong plugin for JWT validation with tenant context
    -- Full implementation would be provided during deployment
    local plugin = {
      PRIORITY = 1010,
      VERSION = "1.0.0"
    }
    -- ...

  "tenant-rate-limiter/handler.lua": |
    -- Custom Kong plugin for tenant-aware rate limiting
    -- Full implementation would be provided during deployment
    local plugin = {
      PRIORITY = 900,
      VERSION = "1.0.0"
    }
    -- ...

  "circuit-breaker/handler.lua": |
    -- Custom Kong plugin for implementing circuit breaker pattern
    -- Full implementation would be provided during deployment
    local plugin = {
      PRIORITY = 800,
      VERSION = "1.0.0"
    }
    -- ...

  "tenant-transformer/handler.lua": |
    -- Custom Kong plugin for tenant-aware request/response transformation
    -- Full implementation would be provided during deployment
    local plugin = {
      PRIORITY = 790,
      VERSION = "1.0.0"
    }
    -- ...

  "tenant-monitoring/handler.lua": |
    -- Custom Kong plugin for enhanced monitoring with Prometheus and OpenTelemetry
    -- Full implementation would be provided during deployment
    local plugin = {
      PRIORITY = 700,
      VERSION = "1.0.0"
    }
    -- ...
