apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-error-templates
  namespace: multi-tenant
data:
  5xx.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Service Temporarily Unavailable</title>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
          background-color: #f8f9fa;
          color: #333;
          line-height: 1.6;
          margin: 0;
          padding: 0;
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 100vh;
        }
        .container {
          max-width: 600px;
          padding: 40px;
          background-color: white;
          border-radius: 8px;
          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
          text-align: center;
        }
        h1 {
          color: #e74c3c;
          margin-bottom: 20px;
          font-weight: 500;
        }
        p {
          margin-bottom: 20px;
          font-size: 16px;
        }
        .status {
          display: inline-block;
          padding: 4px 8px;
          background-color: #f8d7da;
          color: #721c24;
          border-radius: 4px;
          font-size: 14px;
          margin-bottom: 20px;
        }
        .error-id {
          color: #6c757d;
          font-size: 12px;
          margin-top: 30px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Service Temporarily Unavailable</h1>
        <div class="status">Status Code: {{ status }}</div>
        <p>We're experiencing some technical difficulties. Our engineering team has been notified and is working to resolve the issue.</p>
        <p>Please try again later or contact support if the problem persists.</p>
        <p class="error-id">Error ID: {{ request_id }}</p>
      </div>
    </body>
    </html>

  4xx.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Request Error</title>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
          background-color: #f8f9fa;
          color: #333;
          line-height: 1.6;
          margin: 0;
          padding: 0;
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 100vh;
        }
        .container {
          max-width: 600px;
          padding: 40px;
          background-color: white;
          border-radius: 8px;
          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
          text-align: center;
        }
        h1 {
          color: #f39c12;
          margin-bottom: 20px;
          font-weight: 500;
        }
        p {
          margin-bottom: 20px;
          font-size: 16px;
        }
        .status {
          display: inline-block;
          padding: 4px 8px;
          background-color: #fff3cd;
          color: #856404;
          border-radius: 4px;
          font-size: 14px;
          margin-bottom: 20px;
        }
        .error-id {
          color: #6c757d;
          font-size: 12px;
          margin-top: 30px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Request Error</h1>
        <div class="status">Status Code: {{ status }}</div>
        <p>{{ message }}</p>
        <p>Please check your request and try again.</p>
        <p class="error-id">Error ID: {{ request_id }}</p>
      </div>
    </body>
    </html>

  429.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Rate Limit Exceeded</title>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
          background-color: #f8f9fa;
          color: #333;
          line-height: 1.6;
          margin: 0;
          padding: 0;
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 100vh;
        }
        .container {
          max-width: 600px;
          padding: 40px;
          background-color: white;
          border-radius: 8px;
          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
          text-align: center;
        }
        h1 {
          color: #3498db;
          margin-bottom: 20px;
          font-weight: 500;
        }
        p {
          margin-bottom: 20px;
          font-size: 16px;
        }
        .status {
          display: inline-block;
          padding: 4px 8px;
          background-color: #d1ecf1;
          color: #0c5460;
          border-radius: 4px;
          font-size: 14px;
          margin-bottom: 20px;
        }
        .retry {
          font-weight: bold;
        }
        .error-id {
          color: #6c757d;
          font-size: 12px;
          margin-top: 30px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Rate Limit Exceeded</h1>
        <div class="status">Status Code: 429</div>
        <p>You've made too many requests in a short period of time.</p>
        <p>Please try again in <span class="retry">{{ retry_after }}</span> seconds or upgrade your subscription for higher limits.</p>
        <p class="error-id">Error ID: {{ request_id }}</p>
      </div>
    </body>
    </html>

  503.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Service Temporarily Unavailable</title>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
          background-color: #f8f9fa;
          color: #333;
          line-height: 1.6;
          margin: 0;
          padding: 0;
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 100vh;
        }
        .container {
          max-width: 600px;
          padding: 40px;
          background-color: white;
          border-radius: 8px;
          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
          text-align: center;
        }
        h1 {
          color: #e74c3c;
          margin-bottom: 20px;
          font-weight: 500;
        }
        p {
          margin-bottom: 20px;
          font-size: 16px;
        }
        .status {
          display: inline-block;
          padding: 4px 8px;
          background-color: #f8d7da;
          color: #721c24;
          border-radius: 4px;
          font-size: 14px;
          margin-bottom: 20px;
        }
        .circuit-info {
          background-color: #f8f9fa;
          padding: 15px;
          border-radius: 4px;
          margin: 20px 0;
          text-align: left;
        }
        .retry {
          font-weight: bold;
        }
        .error-id {
          color: #6c757d;
          font-size: 12px;
          margin-top: 30px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Service Temporarily Unavailable</h1>
        <div class="status">Status Code: 503</div>
        <p>The service is currently unavailable due to high error rates.</p>
        <div class="circuit-info">
          <p>Circuit Breaker Status: <strong>{{ circuit_state }}</strong></p>
          <p>Please try again in <span class="retry">{{ retry_after }}</span> seconds.</p>
        </div>
        <p>Our engineering team has been automatically notified.</p>
        <p class="error-id">Error ID: {{ request_id }}</p>
      </div>
    </body>
    </html>
