apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: multi-tenant
data:
  kong.yaml: |
    _format_version: "2.1"
    _transform: true

    # Services for the multi-tenant system
    services:
      - name: auth-service
        url: http://auth-service:3000
        plugins:
          - name: circuit-breaker
            config:
              error_threshold: 50
              window_size: 10
              min_calls: 5
              open_circuit_timeout: 30
              health_check_interval: 5
          - name: tenant-transformer
            config:
              remove_sensitive_headers: true
              add_tenant_headers: true
              sanitize_paths: true
              sanitize_query_params: true
          - name: tenant-monitoring
            config:
              collect_metrics: true
              collect_traces: true
              detailed_status_metrics: true
              detailed_latency_metrics: true
        routes:
          - name: auth-service-route
            paths:
              - /api/v1/auth
            strip_path: false
            preserve_host: true
            protocols:
              - https
              - http

      # ... Additional services would be included here

    # Global plugins applied to all services
    plugins:
      - name: tenant-identifier
        config:
          system_domain: example.com
          cache_ttl: 300
          redis_host: redis
          redis_port: 6379
          redis_timeout: 2000
          redis_database: 0

      - name: prometheus
        config:
          status_code_metrics: true
          latency_metrics: true
          bandwidth_metrics: true
          upstream_health_metrics: true

      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Authorization
            - Content-Type
            - X-Requested-With
            - X-Request-ID
            - X-Tenant-ID
          exposed_headers:
            - X-Request-ID
          credentials: true
          max_age: 3600
          preflight_continue: false

      - name: response-transformer
        config:
          remove:
            headers:
              - X-Powered-By
              - Server
