version: '3.8'

services:
  tenant-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenant-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=system_db
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9092
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
      - redis
    networks:
      - tenant-network

  postgres:
    image: postgres:15
    container_name: tenant-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=system_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - tenant-network

  redis:
    image: redis:alpine
    container_name: tenant-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - tenant-network

volumes:
  postgres-data:
  redis-data:

networks:
  tenant-network:
    driver: bridge
