apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
  namespace: multi-tenant
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      
      zipkin:
        endpoint: 0.0.0.0:9411
      
      jaeger:
        protocols:
          thrift_http:
            endpoint: 0.0.0.0:14268
          grpc:
            endpoint: 0.0.0.0:14250

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      
      attributes:
        actions:
          - key: tenant.id
            from_attribute: X-Tenant-ID
            action: upsert
          - key: tenant.schema
            from_attribute: X-Tenant-Schema
            action: upsert
          - key: service.version
            value: "1.0.0"
            action: upsert
      
      resource:
        attributes:
          - key: service.name
            value: "kong-api-gateway"
            action: upsert
          - key: deployment.environment
            value: "${DEPLOYMENT_ENVIRONMENT}"
            action: upsert

    exporters:
      otlp:
        endpoint: jaeger-collector:4317
        tls:
          insecure: true
      
      elasticsearch:
        endpoints: [ http://elasticsearch:9200 ]
        index: traces
      
      logging:
        loglevel: debug

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      
      pprof:
        endpoint: 0.0.0.0:1777

    service:
      extensions: [health_check, pprof]
      pipelines:
        traces:
          receivers: [otlp, zipkin, jaeger]
          processors: [attributes, resource, batch]
          exporters: [otlp, elasticsearch, logging]
